### ISSUE TITLE
Permissions issues

### ISSUE THREAD

**Issue by mmichon** [pookjw/SidecarPatcher#1]
I'm getting the following error, even those SIP is disabled:
```
mmichon@Mikes-MBAir-2015~/Downloads> sudo ./SidecarPatcher
Password:
Ooops! Something went wrong: Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “SidecarCore” because the volume “Macintosh HD” is read only." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore, NSUnderlyingError=0x7f9ccad05f60 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}}
```

Looking at the code, it's doing something like this, which also has permissions issues:
```
mmichon@Mikes-MBAir-2015/t/SidecarPatcher> sudo cp /tmp/SidecarPatcher/SidecarCore /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: Read-only file system
```

**Comment by pookjw** [comment]
If you can't copy a file to /System even SIP is disabled, that's macOS Catalina issue. Try enabling SIP and disabling SIP.

**Comment by mmichon** [comment]
I've tried enabling then disabling, and it's still the same issue. I thought disabling SIP was supposed to allow writes to `/System` again?

**Comment by pookjw** [comment]
Yep. I don't know why that issue happens...

**Comment by mmichon** [comment]
Looks like it's a new Catalina mount option. This fixed it: `sudo mount -uw /; killall Finder`. Might wanna add that code. Thanks!

**Comment by nairbf** [comment]
Does this still work in 2022
