### ISSUE TITLE
Attempting to enable sidecar on Big Sur 2015 Mac.

### ISSUE THREAD

**Issue by ghost** [pookjw/SidecarPatcher#120]
My current OS for my 2015 Mac is Big Sur, but it is not compatible with Sidecar which is why I'm attempting to get it to work using the files provided. After attempting the "sudo swift SidecarPatcher/main.swift" command, the following message is provided after entering my password:

SidecarPatcher (Version 14)
GitHub : https://github.com/pookjw/SidecarPatcher
mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66
main/main.swift:225: Fatal error: Failed to load SidecarCore.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -interpret SidecarPatcher/main.swift -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -color-diagnostics -target-sdk-version 11.3 -module-name main 
1.	Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
2.	While running user code "SidecarPatcher/main.swift"
0  swift-frontend           0x0000000105905e85 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  swift-frontend           0x0000000105904e78 llvm::sys::RunSignalHandlers() + 248
2  swift-frontend           0x0000000105906446 SignalHandler(int) + 262
3  libsystem_platform.dylib 0x00007fff2063bd7d _sigtramp + 29
4  libsystem_platform.dylib 0x0000000100000000 _sigtramp + 18446603344267723424
5  libsystem_platform.dylib 0x000000010ac6a4ef _sigtramp + 18446603344448513935
6  libsystem_platform.dylib 0x000000010ac65abe _sigtramp + 18446603344448494942
7  swift-frontend           0x0000000100b8949b llvm::orc::runAsMain(int (*)(int, char**), llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, llvm::Optional<llvm::StringRef>) + 1387
8  swift-frontend           0x0000000100b6da4a swift::RunImmediately(swift::CompilerInstance&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, swift::IRGenOptions const&, swift::SILOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >&&) + 14474
9  swift-frontend           0x0000000100b34375 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 2421
10 swift-frontend           0x0000000100b260ab swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 7275
11 swift-frontend           0x0000000100aa7e82 main + 1266
12 libdyld.dylib            0x00007fff20611f5d start + 1
Illegal instruction: 4
Willems-MacBook-Pro:~ uuuuugh$ 

Is this method of enabling side car not optimized for the Big Sur OS? I've attempted to get it to work since it's on a 2015 Mac, but it's not wanting to work here because of the new OS.

**Comment by Filtar2000** [comment]
Same error for me

**Comment by Filtar2000** [comment]
How did you solve it? I have a 2014 macbook pro running big sur

**Comment by El-Napster** [comment]
Did you find the solution?

**Comment by Librivore** [comment]
Yeah, same issue here. Has anyone found a solution? Thanks for your help!

**Comment by LexGolubkin** [comment]
Same issue. Also I have found that there are was not file SidecarCore by path /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/. And was not before run the swift script. I’m not a swift dev, could missing file indicate something? (Macbook Pro mid 2015 Intel Iris Pro, OS Monterey 12.6.7)

**Comment by Git-MK7** [comment]
why did u close if u didnt find the solution?
