### ISSUE TITLE
does not work in iMac Late 2013 running Catalina

### ISSUE THREAD

**Issue by mhykgyver** [pookjw/SidecarPatcher#140]
Got this error when I run main.swift:

[/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/swift/Swift.swiftmodule/x86_64-apple-macos.swiftinterface:21465:21: error: module 'Builtin' has no member named 'convertUnownedUnsafeToGuaranteed'
    return try body(Builtin.convertUnownedUnsafeToGuaranteed(fakeBase,
                    ^~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/swift/Swift.swiftmodule/x86_64-apple-macos.swiftinterface:25020:10: error: 'init(_:)' is only available in macOS 11.0 or newer
    self.init(Substring(text))
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/swift/Swift.swiftmodule/x86_64-apple-macos.swiftinterface:25020:10: note: add 'if #available' version check
    self.init(Substring(text))
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/swift/Swift.swiftmodule/x86_64-apple-macos.swiftinterface:25018:21: note: add @available attribute to enclosing initializer
  @inlinable public init?<S>(_ text: S) where S : Swift.StringProtocol {
                    ^
<unknown>:0: error: failed to load module 'Swift'](url)

**Comment by mhykgyver** [comment]
after updating xcode commandline tools, it worked....thanks

**Comment by Git-MK7** [comment]
> after updating xcode commandline tools, it worked....thanks

how did u update?
