### ISSUE TITLE
HEVC

### ISSUE THREAD

**Issue by gatherKnowledge** [pookjw/SidecarPatcher#16]
https://discussionskorea.apple.com/thread/250722745

In this article, They said that CPUs under Intel 6th model don't support HEVC Encoding.
so, I think it could make a problem.  what do you think?

**Comment by w0lfschild** [comment]
There is literally no way around this problem.

If you use this on an older mac computer the video is gonna look like trash. There's no way around that and it's 100% the reason why these devices are blacklisted in the first place.

**Comment by HyungjinKim** [comment]
Wasn't the side car shown in high definition in Beta1? I think we've implemented it software and then switched to HEVC.

**Comment by kingkong991** [comment]
I dont try it on beta..
is it good on beta version?

**Comment by b3z** [comment]
no @kingkong991 but just hypothetically -  are we forced to use HEVC?

**Comment by cooleyandy** [comment]
It's a shame there's no way to switch to h264 instead with higher bitrate.

Other apps like Duet is able to do it with older macs. I'm surprised(not surprised) Apple is limiting this to newer macs.

**Comment by xtrime-ru** [comment]
> In this article, They said that CPUs under Intel 6th model don't support HEVC Encoding.
> so, I think it could make a problem. what do you think?

I think both devices should support HEVC. i have stream quality issues with: ipad air 2 (no HEVC support), and macbook air 2018 (should have HEVC support).
