### ISSUE TITLE
Killed: 9 in bash or zsh: killed

### ISSUE THREAD

**Issue by dasternd** [pookjw/SidecarPatcher#22]
After run **_sudo /path/to/SidecarPatcher_** and enter password, terminal write result: **Killed: 9** in bash or **zsh: killed** in zsh

**Comment by pookjw** [comment]
![Image](https://live.staticflickr.com/65535/48976427898_1185b8ff24_o.png)

Seems like Apple defined my program as malware. You should build [code](https://github.com/pookjw/SidecarPatcher/blob/master/main.swift) yourself to avoid this. I will update to solve this issue.

**Comment by pookjw** [comment]
Updated README.md https://github.com/pookjw/SidecarPatcher/commit/01d948a245431a9e26098374532c298dd6f1f98d

**Comment by dasternd** [comment]
Fine! That's worked. But picture flickers.
