### ISSUE TITLE
MacBook Pro (Retina, 13-inch, Late 2013),10.15 Beta 9 not work

### ISSUE THREAD

**Issue by wdongxv** [pookjw/SidecarPatcher#3]
Issues 1:
Can open "Sidecar" in "System Preferences",but connect option is empty.

Issues 2:
In "Terminal" and another applications , press some keys to crash immediately , such as:  Command + C , Arrow up ...
Cash Log
```
Process:               Terminal [3824]
Path:                  /System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
Identifier:            com.apple.Terminal
Version:               2.10 (433)
Build Info:            Terminal-433000000000000~6
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Terminal [3824]
User ID:               501

PlugIn Path:             /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
PlugIn Identifier:       com.apple.sidecar-core
PlugIn Version:          1.0 (202)

Date/Time:             2019-09-26 00:08:44.152 +0800
OS Version:            Mac OS X 10.15 (19A573a)
Report Version:        12
Anonymous UUID:        BA42A62C-EFE6-77BE-A7F0-889D7E865504


Time Awake Since Boot: 620 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x000000010bd937c4
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2
```

**Comment by pookjw** [comment]
Could you try the latest version?

**Comment by Myr7You** [comment]
For the first question :you must make sure your ipad apple id is the same with the macbook apple id .

**Comment by pookjw** [comment]
Same issue here: https://github.com/pookjw/SidecarPatcher/issues/4#issuecomment-536160943

**Comment by Ralle2D** [comment]
Works here with MacBookPro 11,3 (Retina, 15 inch, Late 2013), macOS 10.15 Beta 10 and iPad Air 2. The image on the iPad is a bit washed out and flickering, but I can live with that. Many thanks for the great work and guidance!

**Comment by lucien-guoheng** [comment]
> Works here with MacBookPro 11,3 (Retina, 15 inch, Late 2013), macOS 10.15 Beta 10 and iPad Air 2. The image on the iPad is a bit washed out and flickering, but I can live with that. Many thanks for the great work and guidance!

Could I asked you whether your devices work in wireless mode?
I have mpb 2016 and iPad Air 2, but I found it only works in wired mode, or shows error code 32002

**Comment by Ralle2D** [comment]
iPad Air 2, but I found it only works in wired mode, or shows error code 32002

same thing here, works only in wired mode. Wireless mode shows error code 32002.


Am 7. Oktober 2019 um 08:37:10, lucien-guoheng (notifications@github.com) schrieb:

Works here with MacBookPro 11,3 (Retina, 15 inch, Late 2013), macOS 10.15 Beta 10 and iPad Air 2. The image on the iPad is a bit washed out and flickering, but I can live with that. Many thanks for the great work and guidance!

Could I asked you whether your devices work in wireless mode?
I have mpb 2016 and iPad Air 2, but I found it only works in wired mode, or shows error code 32002

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

--
Ralf Kunefke
Blumenstraße 15
49377 Vechta
Festnetz: 04441/9169634
Mobil: 0171/2122635 
ralle@bitters.de

**Comment by wdongxv** [comment]
@pookjw 
for Issues 2:
restore the "/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore" file, retry run "SidecarPatcher" is fixed.

**Comment by wdongxv** [comment]
work on Catalina release version.
but only usb cable.

**Comment by kingkong991** [comment]
Ưd

> Work on Catalina release version.
> But only usb cable.

Do you got flicker on you ipad?

**Comment by wdongxv** [comment]
> Ưd
> 
> > Work on Catalina release version.
> > But only usb cable.
> 
> Do you got flicker on you ipad?

Yes, Flicker on my iPad.

**Comment by wdongxv** [comment]
I find one way to reduce flicker.
in "DeskTop & Screen Saver", choose anyone in "Colors" of "Secondary Desktop" .

**Comment by kingkong991** [comment]
i still cant find the way to use it, sidecar dont show any devices on it. Even if i connect the cord

**Comment by wdongxv** [comment]
Could you try USB cable?

kingkong991 <notifications@github.com> 于2019年10月9日周三 下午2:32写道：

**Comment by wdongxv** [comment]
> i still cant find the way to use it, sidecar dont show any devices on it. Even if i connect the cord

Could you try USB cable?

**Comment by kingkong991** [comment]
already man :(

**Comment by ilrasta** [comment]
It works, retina 13” late 2013 and iPad 2017, but only via cable.
You have to authorize iPad when connected with Mac in the finder and on iPad

**Comment by delayedsank** [comment]
im using 9th gen iPad and map 2012 mid 13 inch ....no way for usb, only left with wifi..

**Comment by delayedsank** [comment]
n I have same error of 32002
