### ISSUE TITLE
Doesn't work on Catalina 10.15.4

### ISSUE THREAD

**Issue by Tobias-Bauer** [pookjw/SidecarPatcher#48]
When you try installing it on Catalina 10.15.4 it will stop you from opening apps like safari, app store, music and so on. I fixed this issue by copying the old file back via the terminal.

**Comment by imyelmo** [comment]
I have the same issue, related info and findings I got:

**Mac model:**: MacBookPro12,1
**iPad model:**: iPad8,1

**Mac version** (optional): 10.15.4
**iPad version** (optional): 13.4

**Comments:**

I have found the following error related with custom/adhoc identity after signing properly SideCore:

Dyld Error Message:
  Library not loaded: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
  Referenced from: /System/Library/PrivateFrameworks/MarkupUI.framework/Versions/A/MarkupUI
  Reason: no suitable image found.  Did find:
	/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: code signature in (/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore) **not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)**

Might it be necessary extra workaround on the signing process to solve this issue?

**Comment by imyelmo** [comment]
I have the same issue after upgrading Xcode to its last version.

**Comment by traversalnat** [comment]
I have the same issue and it's probably related to the new Apple Signature mechanism.

**Comment by traversalnat** [comment]
There is a solution in https://github.com/ben-z/free-sidecar for 10.15.4 user.

**Comment by pookjw** [comment]
Fixed on Version 14. If you already patched with Version 13, replace SidecarCore to original one and patch again with Version 14.

**Comment by herbit** [comment]
So it will work again with SIP enabled?

**Comment by Tobias-Bauer** [comment]
Version 14 fixed the issue
