### ISSUE TITLE
Doesn't work on 10.15.5

### ISSUE THREAD

**Issue by yellovest** [pookjw/SidecarPatcher#73]
Just update to 10.15.5 and reapplied the patch and no longer can see iPad.  The sidecar option is visible in System Preferences but it does not recognize my iPad.  Worked previously in 10.15.4.

**Comment by jonas27** [comment]
I have the same issue, except that I only started on 10.15.5. The airplay symbol is not showing either in the task bar. There seems to be a fix in GUI version https://github.com/ben-z/free-sidecar (step 8) is it save just to do this
macOS Catalina 10.15.4+ users: Add amfi_get_out_of_my_way=0x1 to NVRAM boot flags, then skip step 9.

**Comment by yellovest** [comment]
I just booted up today and it is working.  I didn't change any settings.  Weird but it is working on my 2012 macbook with 10.15.5.  I haven't installed the supplemental update to 10.5.5 yet.
