### ISSUE TITLE
Software Update server error

### ISSUE THREAD

**Issue by JonTheGreek** [pookjw/SidecarPatcher#99]
I am getting this error upon installation: "Can't install the software because it is not currently available from the Software Update server."

Does this mean I am doing something wrong on my end?

**Comment by JonTheGreek** [comment]
Ok so I have have fixed the issue. I just simply needed to download and install the new Xcode and it worked perfectly. Thank you so much for this awesome little workaround.

**Comment by shimbo393** [comment]
Hi, I installed Xcode, but I still get the same error about the Software Update server

**Comment by shimbo393** [comment]
It says, “no developer tools were found at ‘Applications/Xcode.app’

**Comment by JonTheGreek** [comment]
Did you have SwiftUI installed as well?

**Comment by JonTheGreek** [comment]
https://youtu.be/YJ4FLFL7nUE 

I used this gentleman’s walk through
